-- blob_fire

return {
  ["blob_fire"] = {
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0.85 0.6 0.6 1   0 0.6 0.6 0.4   0 0 0 0]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 14,
        particlelifespread = 2,
        particlesize       = 6,
        particlesizespread = 5,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        size               = 0.1,
        sizegrowth         = 0.1,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[0 0.6 0.6 1   0.3 0.6 0.6 0.4   0.85 0.6 0.6 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 18,
        particlelifespread = 8,
        particlesize       = 9,
        particlesizespread = 4,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1.0, 0]],
        size               = 0.1,
        sizegrowth         = -.1,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

}

