-- blob_trail

return {
  ["blob_trail"] = {
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0.4 0.7 1 1   0.3 0.6 0.8 0.3   0.4 0.7 0.7 0]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 2,
        particlelifespread = 3,
        particlesize       = 3,
        particlesizespread = 6,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        size               = 0.1,
        sizegrowth         = -.35,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[0.2 0.5 0.9 1   0.3 0.6 0.8 0.3   0.4 0.7 0.7 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 2,
        particlelifespread = 4,
        particlesize       = 6,
        particlesizespread = 3,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1.0, 0]],
        size               = 0.1,
        sizegrowth         = -.2,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

}

