-- blood_explode_blue

return {
  ["blood_explode_blue"] = {
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0 0.6 0.6 1   0 0.6 0.6 1   0 0 0 0]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 20,
        particlelifespread = 2,
        particlesize       = 22,
        particlesizespread = 8,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        size               = 0.2,
        sizegrowth         = 3,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[0 0.6 0.6 1   0 0.6 0.6 1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 12,
        particlelifespread = 8,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 1.5,
        particlespeedspread = 3,
        pos                = [[0, 1.0, 0]],
        size               = 0.1,
        sizegrowth         = -.1,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

}

