-- UNITDEF -- CHICKENS1 --
--------------------------------------------------------------------------------

local unitName = "chickens1"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.66000002622604,
  bmcode             = 1,
  brakeRate          = 0.40000000596046,
  buildCostEnergy    = 174,
  buildCostMetal     = 174,
  builder            = false,
  buildTime          = 1740,
  canAttack          = false,
  canGuard           = false,
  canMove            = false,
  canPatrol          = false,
  canstop            = 1,
  category           = [[MOBILE WEAPON NOTAIR NOTSUB NOTSHIP ALL]],
  collisionvolumeoffsets = [[0 -3 0]],
  collisionvolumescales = [[21 30 46]],
  collisionvolumetype = [[box]],
  corpse             = [[dead]],
  defaultmissiontype = [[Standby]],
  description        = [[Spike Spitter]],
  explodeAs          = [[BUG_DEATH]],
  floater            = false,
  footprintX         = 2,
  footprintZ         = 2,
  iconType           = [[chickens]],
  idleAutoHeal       = 20,
  idleTime           = 300,
  leaveTracks        = false,
  maneuverleashlength = 750,
  mass               = 300,
  maxDamage          = 675,
  maxSlope           = 18,
  maxVelocity        = 2.4000000953674,
  maxWaterDepth      = 15,
  movementClass      = [[AKBOT2]],
  name               = [[Spiker]],
  noAutoFire         = false,
  noChaseCategory    = [[VTOL]],
  objectName         = [[chickens.s3o]],
  seismicSignature   = 0,
  selfDestructAs     = [[BUG_DEATH]],
  side               = [[THUNDERBIRDS]],
  sightDistance      = 370,
  smoothAnim         = false,
  sonarDistance      = 720,
  steeringmode       = 2,
  TEDClass           = [[AKBOT2]],
  trackOffset        = 6,
  trackStrength      = 8,
  trackStretch       = 1,
  trackType          = [[ChickenTrack]],
  trackWidth         = 30,
  turninplace        = 0,
  turnRate           = 768,
  unitname           = [[chickens1]],
  upright            = false,
  workerTime         = 0,
  featuredefs = {
    dead = {
      filename           = [[units/chickens1.lua]],
    },
    heap = {
      filename           = [[units/chickens1.lua]],
    },
  },
  sfxtypes = {
    explosiongenerators = {
      [[custom:blood_spray]],
      [[custom:blood_explode]],
      [[custom:dirt]],
    },
  },
  weapondefs = {
    waterweapon = {
      areaofeffect       = 16,
      avoidfriendly      = 0,
      burnblow           = 1,
      collidefriendly    = 0,
      craterboost        = 0,
      cratermult         = 0,
      explosiongenerator = [[custom:dirt]],
      guidance           = 1,
      impulseboost       = 0.12300000339746,
      impulsefactor      = 0.12300000339746,
      lineofsight        = 1,
      model              = [[spike.s3o]],
      name               = [[Sea Spike]],
      noselfdamage       = 1,
      propeller          = 1,
      range              = 690,
      reloadtime         = 9,
      rendertype         = 1,
      selfprop           = 1,
      startvelocity      = 150,
      tolerance          = 32767,
      tracks             = 1,
      turnRate           = 1500,
      turret             = 1,
      waterweapon        = 1,
      weaponacceleration = 25,
      weapontimer        = 4,
      weapontype         = [[TorpedoLauncher]],
      weaponvelocity     = 220,
      damage = {
        default            = 775,
      },
    },
    weapon = {
      areaofeffect       = 16,
      avoidfeature       = 0,
      avoidfriendly      = 0,
      burnblow           = [[true]],
      collidefeature     = [[true]],
      collidefriendly    = [[false]],
      craterboost        = 0,
      cratermult         = 0,
      edgeeffectiveness  = 0,
      explosiongenerator = [[custom:dirt]],
      impulseboost       = 0,
      impulsefactor      = 0.40000000596046,
      interceptedbyshieldtype = 0,
      lineofsight        = [[true]],
      model              = [[spike.s3o]],
      name               = [[Spike]],
      noselfdamage       = [[true]],
      propeller          = 1,
      range              = 350,
      reloadtime         = 2.2000000476837,
      rendertype         = 1,
      selfprop           = [[true]],
      startvelocity      = 300,
      submissile         = 1,
      targetmoveerror    = 0.5,
      turret             = [[true]],
      waterweapon        = [[false]],
      weaponacceleration = 70,
      weapontimer        = 1,
      weapontype         = [[Cannon]],
      weaponvelocity     = 325,
      damage = {
        default            = 466,
        l1bombers          = 600,
        l1fighters         = 600,
        l2bombers          = 600,
        l2fighters         = 600,
      },
    },
  },
  weapons = {
    [1]  = {
      badTargetCategory  = [[VTOL]],
      def                = [[chickens1_weapon]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 120,
    },
    [2]  = {
      def                = [[chickens1_waterweapon]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 160,
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  chickens1_waterweapon = {
    areaOfEffect       = 16,
    avoidFriendly      = false,
    burnblow           = true,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    explosionGenerator = [[custom:dirt]],
    guidance           = true,
    impulseBoost       = 0.12300000339746,
    impulseFactor      = 0.12300000339746,
    lineOfSight        = true,
    model              = [[spike.s3o]],
    name               = [[Sea Spike]],
    noSelfDamage       = true,
    propeller          = 1,
    range              = 690,
    reloadtime         = 9,
    renderType         = 1,
    selfprop           = true,
    startVelocity      = 150,
    tolerance          = 32767,
    tracks             = true,
    turnRate           = 1500,
    turret             = true,
    waterWeapon        = true,
    weaponAcceleration = 25,
    weaponTimer        = 4,
    weaponType         = [[TorpedoLauncher]],
    weaponVelocity     = 220,
    damage = {
      default            = 775,
    },
  },
  chickens1_weapon = {
    areaOfEffect       = 16,
    avoidFeature       = false,
    avoidFriendly      = false,
    burnblow           = false,
    collideFeature     = false,
    collideFriendly    = false,
    craterBoost        = 0,
    craterMult         = 0,
    edgeEffectiveness  = 0,
    explosionGenerator = [[custom:dirt]],
    impulseBoost       = 0,
    impulseFactor      = 0.40000000596046,
    interceptedByShieldType = 0,
    lineOfSight        = false,
    model              = [[spike.s3o]],
    name               = [[Spike]],
    noSelfDamage       = false,
    propeller          = 1,
    range              = 350,
    reloadtime         = 2.2000000476837,
    renderType         = 1,
    selfprop           = false,
    startVelocity      = 300,
    submissile         = true,
    targetMoveError    = 0.5,
    turret             = false,
    waterWeapon        = false,
    weaponAcceleration = 70,
    weaponTimer        = 1,
    weaponType         = [[Cannon]],
    weaponVelocity     = 325,
    damage = {
      default            = 466,
      l1bombers          = 600,
      l1fighters         = 600,
      l2bombers          = 600,
      l2fighters         = 600,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
  dead = {
  },
}
unitDef.featureDefs = featureDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
