-- UNITDEF -- CHICKENP1 --
--------------------------------------------------------------------------------

local unitName = "chickenp1"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 1,
  activateWhenBuilt  = false,
  bmcode             = 1,
  brakeRate          = 0.60000002384186,
  buildCostEnergy    = 6000,
  buildCostMetal     = 200,
  builder            = false,
  buildPic           = [[]],
  buildTime          = 5280,
  canGuard           = false,
  canMove            = false,
  canPatrol          = false,
  canstop            = 1,
  category           = [[MOBILE WEAPON NOTAIR NOTSUB NOTSHIP ALL]],
  collisionvolumeoffsets = [[0 2 0]],
  collisionvolumescales = [[30 38 60]],
  collisionvolumetype = [[box]],
  defaultmissiontype = [[Standby]],
  description        = [[Chicken Flamer]],
  explodeAs          = [[FLAMEBUG_DEATH]],
  footprintX         = 3,
  footprintZ         = 3,
  iconType           = [[chicken]],
  idleAutoHeal       = 25,
  idleTime           = 0,
  leaveTracks        = false,
  maneuverleashlength = 640,
  mass               = 800,
  maxDamage          = 2400,
  maxVelocity        = 2.9000000953674,
  movementClass      = [[CHICKENHKBOT3]],
  name               = [[Bombardier]],
  noAutoFire         = false,
  noChaseCategory    = [[VTOL]],
  objectName         = [[chicken_listener.s3o]],
  seismicSignature   = 0,
  selfDestructAs     = [[FLAMEBUG_DEATH]],
  side               = [[THUNDERBIRDS]],
  sightDistance      = 390,
  smoothAnim         = false,
  steeringmode       = 2,
  TEDClass           = [[KBOT]],
  trackOffset        = 0,
  trackStrength      = 8,
  trackStretch       = 1,
  trackType          = [[ChickenTrack]],
  trackWidth         = 50,
  turninplace        = 0,
  turnRate           = 950,
  unitname           = [[chickenp1]],
  upright            = false,
  workerTime         = 0,
  featuredefs = {
    dead = {
      filename           = [[units/chickenp1.lua]],
    },
    heap = {
      filename           = [[units/chickenp1.lua]],
    },
  },
  sfxtypes = {
    explosiongenerators = {
      [[custom:blood_spray]],
      [[custom:blood_explode]],
      [[custom:dirt]],
    },
  },
  weapondefs = {
    chaseweapon = {
      craterboost        = 0,
      cratermult         = 0,
      endsmoke           = 0,
      explosiongenerator = [[custom:NONE]],
      impulseboost       = 0,
      impulsefactor      = 0,
      lineofsight        = [[true]],
      name               = [[Claws]],
      noselfdamage       = [[true]],
      proximitypriority  = -4,
      range              = 100,
      reloadtime         = 30,
      size               = 0.0010000000474975,
      startsmoke         = 0,
      targetborder       = 1,
      toairweapon        = 0,
      tolerance          = 5000,
      turret             = [[true]],
      weapontype         = [[Cannon]],
      weaponvelocity     = 500,
      damage = {
        default            = 0.0010000000474975,
      },
    },
    flamer = {
      areaofeffect       = 64,
      avoidfeature       = 0,
      avoidfriendly      = 0,
      burst              = 12,
      burstrate          = 0.0099999997764826,
      craterboost        = 0,
      cratermult         = 0,
      endsmoke           = 0,
      firestarter        = 100,
      flamegfxtime       = 1.8999999761581,
      groundbounce       = 1,
      impulseboost       = 0,
      impulsefactor      = 0,
      intensity          = 0.89999997615814,
      lineofsight        = [[true]],
      name               = [[FlameThrower]],
      noselfdamage       = [[true]],
      proximitypriority  = 4,
      randomdecay        = 0.20000000298023,
      range              = 410,
      reloadtime         = 0.69999998807907,
      rendertype         = 5,
      rgbcolor           = [[1 0.95 0.9]],
      rgbcolor2          = [[0.9 0.85 0.8]],
      sizegrowth         = 1.2000000476837,
      smokedelay         = 1,
      soundstart         = [[Flamhvy1]],
      soundtrigger       = 0,
      sprayangle         = 9600,
      startsmoke         = 0,
      targetmoveerror    = 0.0010000000474975,
      toairweapon        = 0,
      tolerance          = 2500,
      turret             = [[true]],
      weapontimer        = 1,
      weapontype         = [[Flame]],
      weaponvelocity     = 300,
      damage = {
        chicken            = 4,
        commanders         = 20,
        default            = 25,
        tinychicken        = 2,
      },
    },
  },
  weapons = {
    [1]  = {
      def                = [[chickenp1_chaseweapon]],
      mainDir            = [[0 0 1]],
      onlyTargetCategory = [[NOTAIR]],
    },
    [2]  = {
      badTargetCategory  = [[VTOL]],
      def                = [[chickenp1_flamer]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 120,
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  chickenp1_chaseweapon = {
    craterBoost        = 0,
    craterMult         = 0,
    endsmoke           = 0,
    explosionGenerator = [[custom:NONE]],
    impulseBoost       = 0,
    impulseFactor      = 0,
    lineOfSight        = false,
    name               = [[Claws]],
    noSelfDamage       = false,
    proximityPriority  = -4,
    range              = 100,
    reloadtime         = 30,
    size               = 0.0010000000474975,
    startsmoke         = 0,
    targetBorder       = 1,
    toAirWeapon        = false,
    tolerance          = 5000,
    turret             = true,
    weaponType         = [[Cannon]],
    weaponVelocity     = 500,
    damage = {
      default            = 0.0010000000474975,
    },
  },
  chickenp1_flamer = {
    areaOfEffect       = 64,
    avoidFeature       = false,
    avoidFriendly      = false,
    burst              = 12,
    burstrate          = 0.0099999997764826,
    craterBoost        = 0,
    craterMult         = 0,
    endsmoke           = 0,
    fireStarter        = 100,
    flameGfxTime       = 1.8999999761581,
    groundbounce       = true,
    impulseBoost       = 0,
    impulseFactor      = 0,
    intensity          = 0.89999997615814,
    lineOfSight        = true,
    name               = [[FlameThrower]],
    noSelfDamage       = false,
    proximityPriority  = 4,
    randomdecay        = 0.20000000298023,
    range              = 410,
    reloadtime         = 0.69999998807907,
    renderType         = 5,
    rgbColor           = [[1 0.95 0.9]],
    rgbColor2          = [[0.9 0.85 0.8]],
    sizeGrowth         = 1.2000000476837,
    smokedelay         = 1,
    soundStart         = [[Flamhvy1]],
    soundTrigger       = false,
    sprayAngle         = 9600,
    startsmoke         = 0,
    targetMoveError    = 0.0010000000474975,
    toAirWeapon        = false,
    tolerance          = 2500,
    turret             = true,
    weaponTimer        = 1,
    weaponType         = [[Flame]],
    weaponVelocity     = 300,
    damage = {
      chicken            = 4,
      commanders         = 20,
      default            = 25,
      tinychicken        = 2,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
