-- UNITDEF -- CHICKENC1 --
--------------------------------------------------------------------------------

local unitName = "chickenc1"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 1.25,
  bmcode             = 1,
  brakeRate          = 2,
  buildCostEnergy    = 5280,
  buildCostMetal     = 170,
  builder            = false,
  buildTime          = 6280,
  canAttack          = false,
  canGuard           = false,
  canMove            = false,
  canPatrol          = false,
  canstop            = 1,
  category           = [[MOBILE WEAPON NOTAIR NOTSUB NOTSHIP ALL]],
  collisionvolumeoffsets = [[0 11 3]],
  collisionvolumescales = [[25 38 64]],
  collisionvolumetype = [[box]],
  corpse             = [[dead]],
  defaultmissiontype = [[Standby]],
  description        = [[All-Terrain Assault]],
  explodeAs          = [[BIGBUG_DEATH]],
  footprintX         = 3,
  footprintZ         = 3,
  iconType           = [[chickenr]],
  leaveTracks        = false,
  maneuverleashlength = 640,
  mass               = 700,
  maxDamage          = 4250,
  maxreversevelocity = 2,
  maxSlope           = 18,
  maxVelocity        = 2.5,
  maxWaterDepth      = 15,
  movementClass      = [[TKBOT3]],
  name               = [[Basilisk]],
  noAutoFire         = false,
  noChaseCategory    = [[VTOL]],
  objectName         = [[chickenc.s3o]],
  seismicSignature   = 3,
  selfDestructAs     = [[BIGBUG_DEATH]],
  side               = [[THUNDERBIRDS]],
  sightDistance      = 512,
  smoothAnim         = false,
  sonarDistance      = 450,
  steeringmode       = 2,
  TEDClass           = [[KBOT]],
  trackOffset        = 0.5,
  trackStrength      = 9,
  trackStretch       = 1,
  trackType          = [[ChickenTrackPointy]],
  trackWidth         = 70,
  turninplace        = 0,
  turnRate           = 400,
  unitname           = [[chickenc1]],
  upright            = false,
  workerTime         = 0,
  featuredefs = {
    dead = {
      filename           = [[units/chickenc1.lua]],
    },
    heap = {
      filename           = [[units/chickenc1.lua]],
    },
  },
  sfxtypes = {
    explosiongenerators = {
      [[custom:blood_spray]],
      [[custom:blood_explode]],
      [[custom:dirt]],
    },
  },
  weapondefs = {
    weapon = {
      accuracy           = 256,
      areaofeffect       = 96,
      avoidfeature       = 0,
      burst              = 3,
      burstrate          = 0.0099999997764826,
      camerashake        = 0,
      craterboost        = 0,
      cratermult         = 0,
      edgeeffectiveness  = 0,
      endsmoke           = 0,
      explosiongenerator = [[custom:blood_explode_blue]],
      impulseboost       = 0.21999999880791,
      impulsefactor      = 0.21999999880791,
      intensity          = 0.69999998807907,
      interceptedbyshieldtype = 1,
      lineofsight        = [[true]],
      name               = [[Blob]],
      noselfdamage       = [[true]],
      range              = 300,
      reloadtime         = 3.5999999046326,
      rendertype         = 4,
      rgbcolor           = [[0.0 0.6 0.6]],
      size               = 8,
      sizedecay          = -0.30000001192093,
      soundhit           = [[junohit2edit]],
      sprayangle         = 512,
      startsmoke         = 0,
      targetmoveerror    = 0.40000000596046,
      tolerance          = 5000,
      turret             = [[true]],
      weapontimer        = 0.20000000298023,
      weapontype         = [[Cannon]],
      weaponvelocity     = 500,
      damage = {
        amphibious         = 335,
        anniddm            = 335,
        antibomber         = 335,
        antifighter        = 335,
        antiraider         = 335,
        atl                = 335,
        blackhydra         = 335,
        chicken            = 105,
        commanders         = 335,
        crawlingbombs      = 335,
        default            = 1250,
        dl                 = 335,
        ["else"]           = 335,
        flakboats          = 335,
        flaks              = 335,
        flamethrowers      = 335,
        gunships           = 235,
        heavyunits         = 335,
        hgunships          = 235,
        krogoth            = 335,
        l1bombers          = 235,
        l1fighters         = 235,
        l1subs             = 335,
        l2bombers          = 235,
        l2fighters         = 235,
        l2subs             = 335,
        l3subs             = 335,
        mechs              = 335,
        mines              = 335,
        nanos              = 335,
        orcone             = 335,
        otherboats         = 335,
        plasmaguns         = 335,
        radar              = 335,
        seadragon          = 335,
        tinychicken        = 105,
        tl                 = 335,
        vtol               = 235,
        vtrans             = 235,
        vulcbuzz           = 335,
      },
    },
  },
  weapons = {
    [1]  = {
      def                = [[chickenc1_weapon]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 110,
    },
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  chickenc1_weapon = {
    accuracy           = 256,
    areaOfEffect       = 96,
    avoidFeature       = false,
    burst              = 3,
    burstrate          = 0.0099999997764826,
    cameraShake        = 0,
    craterBoost        = 0,
    craterMult         = 0,
    edgeEffectiveness  = 0,
    endsmoke           = 0,
    explosionGenerator = [[custom:blood_explode_blue]],
    impulseBoost       = 0.21999999880791,
    impulseFactor      = 0.21999999880791,
    intensity          = 0.69999998807907,
    interceptedByShieldType = 1,
    lineOfSight        = false,
    name               = [[Blob]],
    noSelfDamage       = false,
    range              = 300,
    reloadtime         = 3.5999999046326,
    renderType         = 4,
    rgbColor           = [[0.0 0.6 0.6]],
    size               = 8,
    sizeDecay          = -0.30000001192093,
    soundHit           = [[junohit2edit]],
    sprayAngle         = 512,
    startsmoke         = 0,
    targetMoveError    = 0.40000000596046,
    tolerance          = 5000,
    turret             = false,
    weaponTimer        = 0.20000000298023,
    weaponType         = [[Cannon]],
    weaponVelocity     = 500,
    damage = {
      amphibious         = 335,
      anniddm            = 335,
      antibomber         = 335,
      antifighter        = 335,
      antiraider         = 335,
      atl                = 335,
      blackhydra         = 335,
      chicken            = 105,
      commanders         = 335,
      crawlingbombs      = 335,
      default            = 1250,
      dl                 = 335,
      ["else"]           = 335,
      flakboats          = 335,
      flaks              = 335,
      flamethrowers      = 335,
      gunships           = 235,
      heavyunits         = 335,
      hgunships          = 235,
      krogoth            = 335,
      l1bombers          = 235,
      l1fighters         = 235,
      l1subs             = 335,
      l2bombers          = 235,
      l2fighters         = 235,
      l2subs             = 335,
      l3subs             = 335,
      mechs              = 335,
      mines              = 335,
      nanos              = 335,
      orcone             = 335,
      otherboats         = 335,
      plasmaguns         = 335,
      radar              = 335,
      seadragon          = 335,
      tinychicken        = 105,
      tl                 = 335,
      vtol               = 235,
      vtrans             = 235,
      vulcbuzz           = 335,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
  dead = {
  },
}
unitDef.featureDefs = featureDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
