-- UNITDEF -- EPIC_CHICKENQ --
--------------------------------------------------------------------------------

local unitName = "epic_chickenq"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 3,
  airSightDistance   = 4000,
  autoHeal           = 90,
  bmcode             = 1,
  brakeRate          = 27,
  buildCostEnergy    = 2000000,
  buildCostMetal     = 50000,
  builder            = false,
  buildTime          = 1000000,
  canAttack          = false,
  canGuard           = false,
  canMove            = false,
  canPatrol          = false,
  canstop            = 1,
  cantBeTransported  = false,
  category           = [[ALL HUGE MOBILE NOTDEFENSE NOTHOVERNOTVTOL NOTSUB NOTSUBNOTSHIP NOTVTOL]],
  collisionSphereScale = 1.75,
  collisionvolumeoffsets = [[0 -52 15]],
  collisionvolumescales = [[69 160 180]],
  collisionvolumetest = 1,
  collisionvolumetype = [[box]],
  corpse             = [[dead]],
  defaultmissiontype = [[Standby]],
  description        = [[Clucking Hell!]],
  explodeAs          = [[QUEEN_DEATH]],
  footprintX         = 3,
  footprintZ         = 3,
  iconType           = [[chickenq]],
  leaveTracks        = false,
  maneuverleashlength = 2000,
  mass               = 366666.84375,
  maxDamage          = 2200001,
  maxSlope           = 40,
  maxVelocity        = 4.25,
  maxWaterDepth      = 70,
  movementClass      = [[CHICKQUEEN]],
  name               = [[Epic Chicken Queen]],
  noAutoFire         = false,
  noChaseCategory    = [[VTOL]],
  objectName         = [[epic_chickenq.s3o]],
  pushResistant      = false,
  seismicSignature   = 4,
  selfDestructAs     = [[QUEEN_DEATH]],
  side               = [[THUNDERBIRDS]],
  sightDistance      = 2000,
  smoothAnim         = false,
  steeringmode       = 2,
  TEDClass           = [[KBOT]],
  trackOffset        = 18,
  trackStrength      = 8,
  trackStretch       = 1,
  trackType          = [[ChickenTrack]],
  trackWidth         = 100,
  turninplace        = 0,
  turninplaceanglelimit = 140,
  turninplacespeedlimit = 2.8050000667572,
  turnRate           = 900,
  unitname           = [[epic_chickenq]],
  upright            = false,
  workerTime         = 0,
  customparams = {
  },
  featuredefs = {
    dead = {
      damage             = 384281.6875,
      description        = [[Epic Chicken Queen Wreckage]],
      filename           = [[units/epic_chickenq.lua]],
      metal              = 37500,
    },
    heap = {
      filename           = [[units/epic_chickenq.lua]],
    },
  },
  sfxtypes = {
    explosiongenerators = {
      [[custom:blood_spray]],
      [[custom:blood_explode]],
      [[custom:dirt]],
      [[custom:DODOTRAIL]],
    },
  },
  weaponDefs = nil,
  weapons = {
		[1] = {
			def = [[MELEE]],
			mainDir = [[0 0 1]],
			maxAngleDif = 155,
		},
		[2] = {
			badTargetCategory = [[NOTVTOL]],
			def = [[SPORES1]],
		},
		[3] = {
			badTargetCategory = [[ALL]],
			def = [[SPORES2]],
		},
		[4] = {
			badTargetCategory = [[NOTWEAPON]],
			def = [[SPORES3]],
		},
		[5] = {
			def = [[GOO]],
			mainDir = [[0 0 1]],
			maxAngleDif = 120,
		},
	},
}


--------------------------------------------------------------------------------

local weaponDefs = {
   goo = {
      accuracy           = 1200,
      areaofeffect       = 200,
      avoidfeature       = [[false]],
      avoidfriendly      = [[false]],
      burst              = 22,
      burstrate          = 0.050000000745058,
      cegtag             = [[ROCKTRAIL]],
      collidefriendly    = [[false]],
      craterareaofeffect = 200,
      craterboost        = 0,
      cratermult         = 0,
      edgeeffectiveness  = 0.5,
      endsmoke           = 0,
      explosiongenerator = [[custom:gundam_MISSILE_EXPLOSION]],
      impulseboost       = 0,
      impulsefactor      = 0,
      intensity          = 0.69999998807907,
      interceptedbyshieldtype = 1,
      lineofsight        = [[false]],
      minbarrelangle     = -30,
      model              = [[SGreyRock1.S3O]],
      name               = [[Blob]],
      noselfdamage       = [[false]],
      proximitypriority  = -4,
      range              = 1200,
      reloadtime         = 6.5,
      rendertype         = 4,
      rgbcolor           = [[0.1 0.6 1]],
      size               = 8,
      sizedecay          = 0,
      soundhit           = [[xplomed2]],
      soundhitwet        = [[sizzle]],
      soundhitwetvolume  = 0.5,
      soundstart         = [[bigchickenroar]],
      sprayangle         = 4096,
      startsmoke         = 0,
      tolerance          = 5000,
      turret             = [[false]],
      weapontimer        = 0.20000000298023,
      weaponvelocity     = 900,
      damage = {
		bombers = 14999,
		chicken = 400,
		default = 1000,
		experimental_land = 4000,
		experimental_ships = 4000,
		fighters = 14999,
		flak_resistant = 4999,
		tinychicken = 200,
		unclassed_air = 14999,
      },
    },
    melee = {
      areaofeffect       = 60,
      avoidfeature       = [[false]],
      avoidfriendly      = [[false]],
      camerashake        = 0,
      collidefriendly    = [[false]],
      craterareaofeffect = 0,
      craterboost        = 0,
      cratermult         = 0,
      endsmoke           = 0,
      explosiongenerator = [[custom:NONE]],
      impulseboost       = 1.5,
      impulsefactor      = 1.5,
      lineofsight        = [[false]],
      name               = [[ChickenClaws]],
      noselfdamage       = [[false]],
      proximitypriority  = -9,
      range              = 320,
      reloadtime         = 0.44999998807907,
      size               = 0,
      soundhitwet        = [[splssml]],
      soundhitwetvolume  = 0.60000002384186,
      soundstart         = [[bigchickenbreath]],
      startsmoke         = 0,
      tolerance          = 5000,
      turret             = [[false]],
      waterweapon        = [[false]],
      weapontype         = [[Cannon]],
      weaponvelocity     = 2500,
      damage = {
        	bombers = 14999,
		chicken = 0.001,
		default = 2000,
		experimental_land = 4000,
		experimental_ships = 4000,
		fighters = 14999,
		flak_resistant = 4999,
		tinychicken = 0.001,
		unclassed_air = 14999,
      },
    },
    spores1 = {
      areaofeffect       = 96,
      avoidfeature       = [[false]],
      avoidfriendly      = [[false]],
      burnblow           = [[true]],
      burst              = 1,
      burstrate          = 0.10999999940395,
      collidefriendly    = [[false]],
      craterareaofeffect = 0,
      craterboost        = 0,
      cratermult         = 0,
      dance              = 20,
      explosiongenerator = [[custom:QUEENSPIKES]],
      firestarter        = 0,
      flighttime         = 5,
      groundbounce       = [[true]],
      guidance           = [[false]],
      heightmod          = 0.5,
      impulseboost       = 0,
      impulsefactor      = 0.40000000596046,
      interceptedbyshieldtype = 0,
      lineofsight        = [[false]],
      metalpershot       = 0,
      model              = [[spike.s3o]],
      name               = [[Missiles]],
      noselfdamage       = [[false]],
      proximitypriority  = 3,
      range              = 900,
      reloadtime         = 0.15000000596046,
      rendertype         = 1,
      selfprop           = [[false]],
      smokedelay         = 0.10000000149012,
      smoketrail         = [[false]],
      soundhit           = [[xplosml2]],
      soundhitwet        = [[splsmed]],
      soundhitwetvolume  = 0.60000002384186,
      startsmoke         = 1,
      startvelocity      = 300,
      texture1           = [[]],
      texture2           = [[sporetrail]],
      tolerance          = 10000,
      tracks             = [[false]],
      trajectoryheight   = 2,
      turnRate           = 48000,
      turret             = [[false]],
      waterweapon        = [[false]],
      weaponacceleration = 200,
      weapontype         = [[MissileLauncher]],
      weaponvelocity     = 4000,
      wobble             = 64000,
      damage = {
		bombers = 450,
		default = 285,
		fighters = 450,
		flak_resistant = 150,
		unclassed_air = 450,
      },
    },
    spores2 = {
      areaofeffect       = 96,
      avoidfeature       = [[false]],
      avoidfriendly      = [[false]],
      burnblow           = [[true]],
      burst              = 9,
      burstrate          = 0.090000003576279,
      collidefriendly    = [[false]],
      craterareaofeffect = 0,
      craterboost        = 0,
      cratermult         = 0,
      dance              = 20,
      explosiongenerator = [[custom:QUEENSPIKES]],
      firestarter        = 0,
      flighttime         = 5,
      groundbounce       = [[true]],
      guidance           = [[false]],
      heightmod          = 0.5,
      impulseboost       = 0,
      impulsefactor      = 0.40000000596046,
      interceptedbyshieldtype = 0,
      lineofsight        = [[false]],
      metalpershot       = 0,
      model              = [[spike.s3o]],
      name               = [[Missiles]],
      noselfdamage       = [[false]],
      range              = 700,
      reloadtime         = 6,
      rendertype         = 1,
      selfprop           = [[false]],
      smokedelay         = 0.10000000149012,
      smoketrail         = [[false]],
      soundhit           = [[xplosml2]],
      soundhitwet        = [[splsmed]],
      soundhitwetvolume  = 0.60000002384186,
      startsmoke         = 1,
      startvelocity      = 200,
      texture1           = [[]],
      texture2           = [[sporetrail]],
      tolerance          = 10000,
      tracks             = [[false]],
      trajectoryheight   = 2,
      turnRate           = 48000,
      turret             = [[false]],
      waterweapon        = [[false]],
      weaponacceleration = 200,
      weapontype         = [[MissileLauncher]],
      weaponvelocity     = 4000,
      wobble             = 64000,
      damage = {
        default            = 700,
      },
    },
    spores3 = {
      areaofeffect       = 64,
      avoidfeature       = [[false]],
      avoidfriendly      = [[false]],
      burnblow           = [[true]],
      burst              = 45,
      burstrate          = 0.20000000298023,
      collidefriendly    = [[false]],
      craterareaofeffect = 0,
      craterboost        = 0,
      cratermult         = 0,
      dance              = 20,
      explosiongenerator = [[custom:QUEENSPIKES]],
      firestarter        = 0,
      flighttime         = 5,
      groundbounce       = [[true]],
      guidance           = [[false]],
      heightmod          = 0.5,
      impulseboost       = 0,
      impulsefactor      = 0.40000000596046,
      interceptedbyshieldtype = 0,
      lineofsight        = [[false]],
      metalpershot       = 0,
      model              = [[spike.s3o]],
      name               = [[Missiles]],
      noselfdamage       = [[false]],
      proximitypriority  = -3,
      range              = 700,
      reloadtime         = 30,
      rendertype         = 1,
      selfprop           = [[false]],
      smokedelay         = 0.10000000149012,
      smoketrail         = [[false]],
      soundhit           = [[xplosml2]],
      soundhitwet        = [[splssml]],
      soundhitwetvolume  = 0.60000002384186,
      startsmoke         = 1,
      startvelocity      = 400,
      texture1           = [[]],
      texture2           = [[sporetrail]],
      tolerance          = 10000,
      tracks             = [[false]],
      trajectoryheight   = 2,
      turnRate           = 48000,
      turret             = [[false]],
      waterweapon        = [[false]],
      weaponacceleration = 200,
      weapontype         = [[MissileLauncher]],
      weaponvelocity     = 4000,
      wobble             = 64000,
      damage = {
		bombers = 450,
		default = 285,
		fighters = 450,
		flak_resistant = 150,
		unclassed_air = 450,
      },
    },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

local featureDefs = {
	DEAD = {
	},
	HEAP = {
	},
}
unitDef.featureDefs = featureDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
